import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
const db=new PGlite();
await db.exec(`create role anon; create role authenticated; create role service_role; create schema auth; create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
create table profiles(id uuid primary key,role text,status text);
create table businesses(id uuid primary key,is_archived boolean not null default false,agreement_status text);
create table business_sale_files(id uuid primary key,business_id uuid references businesses(id),file_type text,storage_path text,status text,deleted_at timestamptz);
create table business_file_meta(id uuid primary key,business_id uuid references businesses(id));
create table matches(id uuid primary key,business_id uuid references businesses(id));
grant select on profiles to authenticated;grant all on business_sale_files to authenticated;
insert into businesses values('11111111-1111-1111-1111-111111111111',false,'יש הסכם חתום'),('22222222-2222-2222-2222-222222222222',false,'אין הסכם');`);
await db.exec(await readFile(new URL('../../supabase/migrations/20261001130324_seller_portal.sql',import.meta.url),'utf8'));
await db.exec(await readFile(new URL('../../supabase/migrations/20261003170000_seller_portal_hardening.sql',import.meta.url),'utf8'));
const blocked=async sql=>{await assert.rejects(()=>db.exec(sql));};
await blocked(`insert into seller_portal_accounts(business_id,username,password_hash) values('22222222-2222-2222-2222-222222222222','34567','hash')`);
await db.exec(`insert into seller_portal_accounts(id,business_id,username,password_hash) values('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa','11111111-1111-1111-1111-111111111111','34567','hash');insert into seller_portal_sessions(account_id,token_hash,expires_at) values('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa','token',now()+interval '1 hour');`);
await blocked(`insert into seller_portal_accounts(business_id,username,password_hash) values('11111111-1111-1111-1111-111111111111','34567','hash')`);
const activitySession=(await db.query('select id from seller_portal_sessions')).rows[0].id;
await db.exec(`update seller_portal_sessions set last_activity_measure_at=clock_timestamp()-interval '35 seconds'`);
const delta=(await db.query(`select seller_portal_record_activity('${activitySession}','aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa','documents',90,'heartbeat') n`)).rows[0].n;
assert.ok(delta>=35&&delta<=36);
const repeated=(await db.query(`select seller_portal_record_activity('${activitySession}','aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa','documents',90,'heartbeat') n`)).rows[0].n;
assert.equal(repeated,0);
assert.equal((await db.query('select active_seconds from seller_portal_sessions')).rows[0].active_seconds,delta);
await blocked(`select seller_portal_record_activity('${activitySession}','aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa','unknown',10,'heartbeat')`);

await db.exec(`update businesses set is_archived=true where id='11111111-1111-1111-1111-111111111111'`);
assert.equal((await db.query('select status from seller_portal_accounts')).rows[0].status,'archived');
assert.ok((await db.query('select revoked_at from seller_portal_sessions')).rows[0].revoked_at);
await blocked(`select seller_portal_record_activity('${activitySession}','aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa','home',10,'heartbeat')`);
await db.exec(`update businesses set is_archived=false where id='11111111-1111-1111-1111-111111111111'`);
assert.equal((await db.query('select status from seller_portal_accounts')).rows[0].status,'archived');
await db.exec(`update seller_portal_accounts set status='active';update businesses set agreement_status='אין הסכם' where id='11111111-1111-1111-1111-111111111111'`);
assert.equal((await db.query('select status from seller_portal_accounts')).rows[0].status,'blocked');
for(let i=0;i<8;i++)assert.equal((await db.query("select seller_portal_take_attempt('key',8) allowed")).rows[0].allowed,true);
assert.equal((await db.query("select seller_portal_take_attempt('key',8) allowed")).rows[0].allowed,false);
for(const role of ['anon','authenticated']){
 await db.exec(`set role ${role}`);await blocked('select * from seller_portal_accounts');await blocked('select * from seller_portal_sessions');await blocked("select seller_portal_take_attempt('key',8)");await db.exec('reset role');
}
await db.exec(`set role authenticated`);
await blocked(`insert into business_sale_files(id,business_id,portal_visible) values('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb','11111111-1111-1111-1111-111111111111',true)`);
await db.exec('reset role');
const result=(await db.query("select relname,relrowsecurity from pg_class where relname like 'seller_portal_%' and relkind='r'")).rows;
assert.equal(result.length,6);assert.ok(result.every(r=>r.relrowsecurity));
// Hardening migration: single-use activation, expiry, global ceiling check, pruning.
await db.exec(`update businesses set is_archived=false,agreement_status='יש הסכם חתום' where id='11111111-1111-1111-1111-111111111111';update seller_portal_accounts set status='active',password_hash='!pending-activation',activation_token_hash='tok1',activation_expires_at=now()+interval '1 hour' where id='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'`);
let act=(await db.query(`select * from seller_portal_activate('tok1','600000.s.h1','sess-act-1',now()+interval '8 hours')`)).rows;
assert.equal(act.length,1);assert.equal(act[0].username,'34567');
assert.equal((await db.query(`select * from seller_portal_activate('tok1','600000.s.h2','sess-act-2',now()+interval '8 hours')`)).rows.length,0,'activation link is single use');
let acc=(await db.query(`select password_hash,activation_token_hash,must_change_password from seller_portal_accounts where id='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'`)).rows[0];
assert.equal(acc.password_hash,'600000.s.h1');assert.equal(acc.activation_token_hash,null);assert.equal(acc.must_change_password,false);
assert.equal((await db.query(`select count(*)::int n from seller_portal_sessions where account_id='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' and revoked_at is null`)).rows[0].n,1,'activation revokes older sessions and opens exactly one');
await db.exec(`update seller_portal_accounts set activation_token_hash='tok2',activation_expires_at=now()-interval '1 minute' where id='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'`);
assert.equal((await db.query(`select * from seller_portal_activate('tok2','600000.s.h3','sess-act-3',now()+interval '8 hours')`)).rows.length,0,'expired link rejected');
await db.exec(`update seller_portal_accounts set activation_token_hash='tok3',activation_expires_at=now()+interval '1 hour' where id='aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa';update businesses set agreement_status='אין הסכם' where id='11111111-1111-1111-1111-111111111111'`);
assert.equal((await db.query(`select * from seller_portal_activate('tok3','600000.s.h4','sess-act-4',now()+interval '8 hours')`)).rows.length,0,'no activation without signed agreement');
await db.exec(`update businesses set agreement_status='יש הסכם חתום' where id='11111111-1111-1111-1111-111111111111'`);
await db.exec(`insert into seller_portal_rate_limits(key_hash,attempts) values('global-test',5)`);
assert.equal((await db.query(`select seller_portal_attempts_exceeded('global-test',5) x`)).rows[0].x,true);
assert.equal((await db.query(`select seller_portal_attempts_exceeded('global-test',6) x`)).rows[0].x,false);
await db.exec(`insert into seller_portal_rate_limits(key_hash,window_start,attempts) values('old-key',now()-interval '2 days',3);
insert into seller_portal_sessions(id,account_id,token_hash,expires_at,revoked_at) values('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb','aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa','old-session',now()-interval '100 days',now()-interval '100 days');
insert into seller_portal_events(account_id,session_id,event_type) values('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa','bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb','login');`);
await db.exec(`select seller_portal_prune()`);
assert.equal((await db.query(`select count(*)::int n from seller_portal_rate_limits where key_hash='old-key'`)).rows[0].n,0,'old rate-limit rows pruned');
assert.equal((await db.query(`select count(*)::int n from seller_portal_sessions where id='bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb'`)).rows[0].n,0,'old sessions pruned');
assert.ok((await db.query(`select count(*)::int n from seller_portal_events where event_type='login' and session_id is null`)).rows[0].n>=1,'audit events kept after session pruning');
await db.exec(`delete from businesses where id='11111111-1111-1111-1111-111111111111'`);
assert.equal((await db.query('select business_id,status from seller_portal_accounts')).rows[0].business_id,null);
assert.equal((await db.query('select status from seller_portal_accounts')).rows[0].status,'blocked');
assert.ok((await db.query('select count(*) n from seller_portal_events')).rows[0].n>0);
console.log('PASS: migration, hardening (single-use activation, expiry, signed-agreement gate, global ceiling, pruning keeps audit), agreement gate, archive revocation, restore stays blocked, uniqueness, atomic rate limits, RLS, no direct API access, manager file approval');await db.close();

