import {createHandler} from '../../supabase/functions/seller-portal-api/handler.ts';
import {digest,hashPassword} from '../../supabase/functions/seller-portal-api/security.ts';
const assert=(v:unknown,m='assertion failed')=>{if(!v)throw Error(m);};
const biz='11111111-1111-1111-1111-111111111111',other='22222222-2222-2222-2222-222222222222',file='33333333-3333-3333-3333-333333333333';
function mock(tables:Record<string,any[]>){
 const rates:Record<string,number>={};
 const db:any={auth:{getUser:(token:string)=>Promise.resolve({data:{user:token==='admin'||token==='agent'?{id:token}:null},error:null})},rpc:(_name:string,{p_key,p_max}:any)=>Promise.resolve({data:(rates[p_key]=(rates[p_key]||0)+1)<=p_max,error:null}),storage:{from:()=>({download:()=>Promise.resolve({data:new Blob(['%PDF-1.7\nTEST ORIGINAL BYTES']),error:null})})}};
 db.from=(table:string)=>{const filters:((r:any)=>boolean)[]=[],rows=tables[table]||=[];let operation='select',value:any,single=false,limit=Infinity;
 const q:any={select:()=>q,eq:(k:string,v:any)=>{filters.push(r=>r[k]===v);return q;},neq:(k:string,v:any)=>{filters.push(r=>r[k]!==v);return q;},is:(k:string,v:any)=>{filters.push(r=>r[k]==v);return q;},in:(k:string,v:any[])=>{filters.push(r=>v.includes(r[k]));return q;},gte:(k:string,v:any)=>{filters.push(r=>r[k]>=v);return q;},lte:(k:string,v:any)=>{filters.push(r=>r[k]<=v);return q;},order:()=>q,limit:(n:number)=>{limit=n;return q;},maybeSingle:()=>{single=true;return q;},single:()=>{single=true;return q;},insert:(v:any)=>{operation='insert';value=v;return q;},update:(v:any)=>{operation='update';value=v;return q;},upsert:(v:any)=>{operation='insert';value=v;return q;},then:(resolve:any,reject:any)=>{try{let found=rows.filter(r=>filters.every(f=>f(r))).slice(0,limit);if(operation==='insert'){const r={id:crypto.randomUUID(),created_at:new Date().toISOString(),last_activity_at:new Date().toISOString(),...value};rows.push(r);found=[r];}if(operation==='update')found.forEach(r=>Object.assign(r,value));return Promise.resolve({data:single?found[0]||null:found,error:null}).then(resolve,reject);}catch(e){return Promise.reject(e).then(resolve,reject);}}};return q;};return db;
}
async function fixture(){const tables:any={businesses:[{id:biz,internal_name:'TEST BUSINESS',owner_name:'TEST OWNER',owner_phone:'',city:'TEST',is_archived:false,agreement_status:'יש הסכם חתום'}],seller_portal_accounts:[{id:'account',business_id:biz,username:'23456',status:'active',password_hash:await hashPassword('Correct234!'),must_change_password:false}],seller_portal_sessions:[{id:'session',account_id:'account',token_hash:await digest('test-token'),expires_at:new Date(Date.now()+3600000).toISOString(),last_activity_at:new Date().toISOString()}],business_sale_files:[{id:file,business_id:biz,status:'active',deleted_at:null,portal_visible:true,file_type:'application/pdf',file_name:'test.pdf',storage_path:biz+'/test.pdf',portal_kind:'document'},{id:'44444444-4444-4444-4444-444444444444',business_id:other,status:'active',portal_visible:true,file_type:'application/pdf',storage_path:other+'/secret.pdf'}],matches:[],profiles:[{id:'admin',role:'admin',status:'active'},{id:'agent',role:'agent',status:'active'}]};const handle=createHandler(mock(tables),{origins:['https://preview.test'],portalUrl:'https://preview.test',phone:'',ipSalt:'test-only-salt'});const request=(action:string,payload={},headers={})=>handle(new Request('https://api.test',{method:'POST',headers:{'Content-Type':'application/json','origin':'https://preview.test','x-seller-token':'test-token',...headers},body:JSON.stringify({action,...payload})}));return {tables,request,handle};}
Deno.test('file endpoint returns original PDF and rejects another business, revoked approval and unsigned requests',async()=>{const f=await fixture();let r=await f.request('file',{file_id:file,mode:'view'});assert(r.status===200);assert(await r.text()==='%PDF-1.7\nTEST ORIGINAL BYTES');r=await f.request('file',{file_id:'44444444-4444-4444-4444-444444444444',mode:'view'});assert(r.status===404);f.tables.business_sale_files[0].portal_visible=false;assert((await f.request('file',{file_id:file,mode:'download'})).status===404);assert((await f.request('dashboard',{}, {'x-seller-token':''})).status===401);});
Deno.test('existing session is denied immediately after archive or account blocking',async()=>{const f=await fixture();f.tables.businesses[0].is_archived=true;assert((await f.request('dashboard')).status===401);f.tables.businesses[0].is_archived=false;f.tables.seller_portal_accounts[0].status='blocked';assert((await f.request('dashboard')).status===401);});
Deno.test('seller cannot call CRM admin endpoints and agents cannot manage portal',async()=>{const f=await fixture();assert((await f.request('admin_list')).status===401);assert((await f.request('admin_list',{}, {authorization:'Bearer agent'})).status===403);assert((await f.request('admin_list',{}, {authorization:'Bearer admin'})).status===200);});
Deno.test('dashboard includes no private paths, hashes, buyer contacts or unapproved matches',async()=>{const f=await fixture();f.tables.matches=[{id:'match',business_id:biz,buyer_id:'buyer',counterparty_type:'buyer',created_at:'2026-01-01'}];const r=await f.request('dashboard');const d=await r.json();assert(d.matches.length===0);assert(d.files.length===1);const serialized=JSON.stringify(d);assert(!serialized.includes('storage_path')&&!serialized.includes('password_hash')&&!serialized.includes('secret.pdf'));});
Deno.test('login has generic errors and rate limiting across unknown user attempts',async()=>{const f=await fixture();const wrong=await f.request('login',{username:'23456',password:'wrong'});const missing=await f.request('login',{username:'99999',password:'wrong'});assert(JSON.stringify(await wrong.json())===JSON.stringify(await missing.json()));for(let i=0;i<7;i++)await f.request('login',{username:'99999',password:'wrong'});assert((await f.request('login',{username:'99999',password:'wrong'})).status===429);});
Deno.test('first login must change password before retrieving business information',async()=>{const f=await fixture();f.tables.seller_portal_accounts[0].must_change_password=true;assert((await f.request('dashboard')).status===403);assert((await f.request('change_password',{password:'abc'})).status===400);assert((await f.request('change_password',{password:'SafePassword234!'})).status===200);assert((await f.request('dashboard')).status===200);});
Deno.test('disallowed origin never gets authenticated response',async()=>{const f=await fixture();assert((await f.request('dashboard',{}, {origin:'https://evil.test'})).status===403);});
