// 05.10.2026 - Baruch rule: VIP and published materials always use ONLY the latest
// anonymous-summary PDF. Never leave an older PDF live after the summary changed.
import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const html = fs.readFileSync(new URL('../businesses.html', import.meta.url), 'utf8');
const vipJs = fs.readFileSync(new URL('../js/vip-crm-integration.js', import.meta.url), 'utf8');
const sale = fs.readFileSync(new URL('../js/saleFileModule2.js', import.meta.url), 'utf8');
const fnSrc = (src, name) => { const i = src.indexOf(name); assert.ok(i > 0, name); return src.slice(i, src.indexOf('\n}\n', i) + 2); };

const ctx = {};
vm.createContext(ctx);
vm.runInContext(html.slice(html.indexOf('const BSD_ANON_PDF_TAG_RE'), html.indexOf('\n', html.indexOf('const BSD_ANON_PDF_TAG_RE'))) + '\n' + fnSrc(html, 'function bsdAnonPdfFileFreshness') + '\nthis.f = bsdAnonPdfFileFreshness;', ctx);
const fresh = ctx.f;

test('freshness: a tagged PDF is current only when built from the current text', () => {
  const file = { storage_path: 'b/sale-file/exec_summary/1_v3_h0123456789abcdef.pdf', created_at: '2026-01-01T00:00:00Z' };
  assert.equal(fresh(file, '0123456789abcdef', null), true);
  assert.equal(fresh(file, 'ffffffffffffffff', null), false);
  assert.equal(fresh(file, '0123456789abcdef', '2030-01-01T00:00:00Z'), true, 'tag wins over timestamps');
});

test('freshness: an old untagged PDF is compared with the last summary change', () => {
  const file = { storage_path: 'b/sale-file/exec_summary/1_v1.pdf', created_at: '2026-09-30T16:02:08Z' };
  assert.equal(fresh(file, 'x', '2026-10-01T06:26:22Z'), false, 'summary changed after the PDF => stale');
  assert.equal(fresh(file, 'x', '2026-09-01T00:00:00Z'), true);
  assert.equal(fresh(file, 'x', null), null, 'no evidence => unknown, never silently "fresh"');
  assert.equal(fresh(null, 'x', null), false);
});

test('every successful anonymous-summary save refreshes the PDF to the latest', () => {
  assert.match(fnSrc(html, 'async function bsdAfterAnonSaved'), /bsdQueueAnonPdfSync\(bizId\)/);
  const save = fnSrc(html, 'async function saveBiz(e)');
  assert.match(save, /const anonTextSent = !!bizId && !anonBlocked && \(payload\.anon_summary !== undefined \|\| payload\.anon_display_name !== undefined\)/);
  assert.match(save, /if \(anonTextSent\) bsdQueueAnonPdfSync\(bizId\)/);
  assert.match(fnSrc(html, 'async function generateAndSaveSummaryPdf'), /bsdSyncLatestAnonPdf\(bizId, \{ mode: 'generate'/);
});

test('sync: no PDF and not VIP => nothing is created; VIP is only re-pointed when ALREADY published', () => {
  const sync = fnSrc(html, 'async function bsdSyncLatestAnonPdf');
  assert.match(sync, /mode === 'after-save' && !st\.files\.length && !st\.vipPublished\) return \{ ok: true, skipped: 'no_pdf_not_vip' \}/);
  assert.match(sync, /const vipNeedsRepoint = !!\(st\.vipPublished && newest && st\.publication\.anonymous_file_id !== newest\.id\)/);
  const publishCalls = sync.match(/admin_publish_business/g) || [];
  assert.equal(publishCalls.length, 1);
  assert.ok(sync.indexOf('if (vipNeedsRepoint)') < sync.indexOf('admin_publish_business'));
  assert.doesNotMatch(sync, /enabled:\s*false/);
});

test('sync: old versions are soft-deleted only after VIP points at the new file, only by admin/manager', () => {
  const sync = fnSrc(html, 'async function bsdSyncLatestAnonPdf');
  const cleanup = sync.slice(sync.indexOf('let retired'));
  assert.match(cleanup, /if \(vipError\) cleanupSkipped = 'vip_not_updated'/);
  assert.match(cleanup, /!bsdIsAdminOrManagerNow\(\) \|\| !st\.vipKnown/);
  assert.match(cleanup, /update\(\{ status: 'deleted', deleted_at:/);
  assert.match(cleanup, /\.eq\('document_type', 'anonymous_summary'\)/);
  assert.doesNotMatch(sync, /\.delete\(/, 'never a hard delete');
  assert.doesNotMatch(sync, /storage\.from\([^)]*\)\.remove/, 'storage objects are kept');
  assert.match(sync, /sfLogAudit\(bizId, 'sync_latest_anon_pdf'/);
});

test('sale file: auto PDFs carry the text fingerprint and return the new id', () => {
  const f = fnSrc(sale, 'async function saveAutoGeneratedSummaryPdf');
  assert.match(f, /_h\$\{String\(opts\.pathTag\)\.toLowerCase\(\)\}/);
  assert.match(f, /return \{ versionNum, path, fileName, id \}/);
});

test('VIP box: stale PDF cannot be newly published, publishing always uses the latest file', () => {
  assert.match(vipJs, /const lockPublish=noFiles \|\| \(stale && !enabled\)/);
  assert.match(vipJs, /chosen:files\[0\]\?\.id \|\| ''/);
  assert.match(vipJs, /ה-PDF ישן מהתקציר/);
  assert.match(vipJs, /ב-VIP מוצג PDF ישן/);
  assert.match(vipJs, /🔄 עדכן ל-PDF האחרון/);
});
