(()=>{'use strict';
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>v?new Date(v).toLocaleDateString('he-IL',{timeZone:'Asia/Jerusalem'}):'';
let token=sessionStorage.getItem('bsd-seller-token')||'',data=null,pdfUrl=null,idleTimer;
const status=message=>{$('status').textContent=message;};
const errors={invalid_credentials:'שם המשתמש או הסיסמה אינם תקינים',try_later:'בוצעו ניסיונות רבים. אפשר לנסות שוב בעוד 15 דקות',unauthorized:'הכניסה פגה. יש להתחבר מחדש',strong_password_required:'יש לבחור סיסמה עם לפחות 10 תווים, אותיות ומספרים',temporarily_unavailable:'השירות אינו זמין כרגע. אפשר לנסות שוב בהמשך'};
async function api(action,payload={},file=false){
 const url=window.SELLER_PORTAL_CONFIG?.apiUrl;
 if(!url)throw Error('סביבת הבדיקה טרם חוברה לשירות המאובטח');
 const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',...(token?{'x-seller-token':token}:{})},body:JSON.stringify({action,...payload})});
 if(file&&r.ok)return r.blob();
 const d=await r.json();if(!r.ok){if(d.error==='password_change_required'){changePassword();throw Error('יש לבחור סיסמה אישית לפני צפייה במידע');}if(r.status===401&&action!=='login')reset();throw Error(errors[d.error]||'לא ניתן להשלים את הפעולה כרגע');}return d;
}
function reset(){document.body.classList.add('is-login');token='';data=null;clearTimeout(idleTimer);sessionStorage.removeItem('bsd-seller-token');$('loginPage').hidden=false;$('dashboard').hidden=true;$('logout').hidden=true;$('dialog').close();closePdf();}
function armIdle(){if(token){clearTimeout(idleTimer);idleTimer=setTimeout(()=>{api('logout').catch(()=>{});reset();status('הכניסה הסתיימה לאחר 30 דקות ללא פעילות');},30*60000);}}
['pointerdown','keydown'].forEach(event=>document.addEventListener(event,armIdle,{passive:true}));
function closePdf(){if(pdfUrl){URL.revokeObjectURL(pdfUrl);pdfUrl=null;}}
function modal(html,pdf=false){closePdf();$('dialog').classList.toggle('pdf-dialog',pdf);$('dialogBody').innerHTML=html;$('dialog').showModal();}
$('closeDialog').onclick=()=>$('dialog').close();$('dialog').addEventListener('close',()=>{closePdf();$('dialogBody').innerHTML='';});
$('showPassword').onclick=()=>{const input=$('loginForm').elements.password;const show=input.type==='password';input.type=show?'text':'password';$('showPassword').textContent=show?'הסתר':'הצג';$('showPassword').setAttribute('aria-label',show?'הסתרת סיסמה':'הצגת סיסמה');};
function changePassword(){modal('<h2>בחירת סיסמה אישית</h2><p>לשמירה על המידע העסקי שלך, יש להחליף את הסיסמה הזמנית בכניסה הראשונה.</p><form id="passwordForm"><label>סיסמה חדשה<input name="password" type="password" minlength="10" maxlength="128" autocomplete="new-password" required></label><p class="muted">לפחות 10 תווים הכוללים אותיות ומספרים</p><button class="primary wide">שמירת הסיסמה</button></form>');$('passwordForm').onsubmit=async e=>{e.preventDefault();try{await api('change_password',{password:e.target.elements.password.value});$('dialog').close();await load();}catch(err){status(err.message);}};}
$('loginForm').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button[type=submit]');button.disabled=true;status('');try{const d=await api('login',{username:e.target.elements.username.value,password:e.target.elements.password.value});token=d.token;sessionStorage.setItem('bsd-seller-token',token);e.target.elements.password.value='';armIdle();if(d.must_change_password)changePassword();else await load();}catch(err){status(err.message);}finally{button.disabled=false;}};
function selectTab(tab){document.querySelectorAll('.tab').forEach(x=>x.hidden=x.id!==tab);document.querySelectorAll('.sidebar [data-tab]').forEach(x=>x.classList.toggle('selected',x.dataset.tab===tab));window.scrollTo({top:0,behavior:'smooth'});}
const emptyDoc='מסמכים שאושרו להצגה על ידי צוות BSD יופיעו כאן.';
const emptyReport='דוחות פעילות שיעודכנו על ידי צוות BSD יופיעו כאן. למידע על פעילות השיווק, ניתן לפנות אלינו.';
const emptyMatch='עדיין אין התאמות שאושרו להצגה באזור האישי. צוות BSD זמין לעדכון ולשאלות.';
function filesHtml(files,report=false){return files.length?files.map(f=>`<div class="file-row"><div><strong>${esc(f.name)}</strong><small>${esc(f.type||'מסמך PDF')} · ${date(f.date)}</small>${f.period_from?`<small>תקופה: ${date(f.period_from)} עד ${date(f.period_to)}</small>`:''}</div><div class="actions"><button data-file="${esc(f.id)}" data-mode="view">צפייה</button><button data-file="${esc(f.id)}" data-mode="download">הורדת PDF</button></div></div>`).join(''):`<p class="empty">${report?emptyReport:emptyDoc}</p>`;}
function matchesHtml(matches){return matches.length?matches.map(m=>`<div class="match-row"><div><strong>${esc(m.name)}</strong>${m.company?`<small>${esc(m.company)}</small>`:''}<small>${date(m.date)} · ${esc(m.status)}</small></div><span class="badge ${m.agreement_status==='חתם'?'signed':''}">הסכם: ${esc(m.agreement_status)}</span></div>`).join(''):`<p class="empty">${emptyMatch}</p>`;}
async function load(){try{data=await api('dashboard');const b=data.business,docs=data.files.filter(f=>f.kind!=='advertising'),reports=data.files.filter(f=>f.kind==='advertising');document.body.classList.remove('is-login');$('loginPage').hidden=true;$('dashboard').hidden=false;$('logout').hidden=false;$('businessName').textContent=b.internal_name;$('hello').textContent=b.owner_name?`שלום, ${b.owner_name}`:'ברוכים הבאים';$('businessMeta').textContent=[b.owner_name,b.owner_phone,b.city].filter(Boolean).join(' · ');$('docCount').textContent=docs.length||'טרם עודכנו';$('matchCount').textContent=data.matches.length||'טרם עודכנו';$('reportCount').textContent=reports.length||'טרם עודכנו';$('documentList').innerHTML=filesHtml(docs);$('reportList').innerHTML=filesHtml(reports,true);$('matchList').innerHTML=matchesHtml(data.matches);$('homeFiles').innerHTML=filesHtml(docs.slice(0,3));$('homeMatches').innerHTML=matchesHtml(data.matches.slice(0,3));$('businessDetails').innerHTML=[['שם העסק',b.internal_name],['איש קשר',b.owner_name],['טלפון',b.owner_phone],['מיקום',b.city]].filter(x=>x[1]).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('');$('updateMessage').textContent=data.update?.message||'ניתן לפנות לצוות BSD לקבלת מידע על תהליך מכירת העסק.';$('updateTitle').textContent=data.update?'עדכון מצוות BSD':'עדכונים אישיים יופיעו כאן';$('updateDate').textContent=date(data.update?.date);const phone=String(data.contact.phone||'').replace(/[^+0-9]/g,'');if(phone){$('phone').href='tel:'+phone;$('phone').textContent=data.contact.phone;$('phone').hidden=false;const wa=phone.startsWith('0')?'972'+phone.slice(1):phone.replace('+','');$('whatsapp').href=`https://wa.me/${wa}?text=${encodeURIComponent('שלום BSD, אני פונה מהאזור האישי של '+b.internal_name)}`;$('whatsapp').hidden=false;}selectTab('home');armIdle();status('');}catch(err){status(err.message);}}
async function openFile(id,mode){status('טוען את הקובץ...');try{const blob=await api('file',{file_id:id,mode,file_source:data.files.find(f=>f.id===id)?.file_source},true),f=data.files.find(f=>f.id===id);const url=URL.createObjectURL(blob);if(mode==='download'){const a=document.createElement('a');a.href=url;a.download=f?.name||'document.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}else{modal(`<h2>${esc(f?.name||'מסמך')}</h2><p class="muted">אם התצוגה אינה מופיעה במכשיר שלך, ניתן לפתוח את הקובץ בחלון נפרד או להוריד אותו.</p><a id="openPdf" target="_blank" rel="noopener">פתיחה בחלון נפרד</a><button data-file="${esc(id)}" data-mode="download">הורדת PDF</button><iframe title="תצוגת מסמך PDF" id="pdfFrame"></iframe>`,true);pdfUrl=url;$('pdfFrame').src=url;$('openPdf').href=url;}status('');}catch(err){status(err.message);}}
document.addEventListener('click',e=>{const tab=e.target.closest('[data-tab]');if(tab)selectTab(tab.dataset.tab);const file=e.target.closest('[data-file]');if(file)openFile(file.dataset.file,file.dataset.mode);const rec=e.target.closest('[data-recovery]');if(rec){const kind=rec.dataset.recovery;modal(`<h2>${kind==='username'?'שחזור שם משתמש':'איפוס סיסמה'}</h2><p>הבקשה תועבר לצוות BSD. פרטי חשבונות אינם נחשפים בטופס זה.</p><form id="recoveryForm"><label>שם המבקש<input name="name" maxlength="100" required autocomplete="name"></label><label>שם העסק<input name="business" maxlength="160" required></label><label>טלפון<input name="phone" type="tel" maxlength="25" required autocomplete="tel"></label><label>הערה אופציונלית<textarea name="message" maxlength="2000"></textarea></label><button class="primary wide">שליחת בקשה</button></form>`);$('recoveryForm').onsubmit=async ev=>{ev.preventDefault();try{await api('recovery',{kind,...Object.fromEntries(new FormData(ev.target))});$('dialog').close();status('הבקשה התקבלה ותועבר לצוות BSD');}catch(err){status(err.message);}};}if(e.target.closest('[data-message]')){modal('<h2>שליחת הודעה לצוות BSD</h2><p>הפנייה תישלח עם שם העסק ופרטי החשבון שלך.</p><form id="messageForm"><label>ההודעה שלך<textarea name="message" maxlength="2000" required rows="5"></textarea></label><button class="primary wide">שליחת הודעה</button></form>');$('messageForm').onsubmit=async ev=>{ev.preventDefault();try{await api('message',{message:ev.target.elements.message.value});$('dialog').close();status('ההודעה התקבלה במערכת BSD');}catch(err){status(err.message);}};}});
$('logout').onclick=async()=>{try{await api('logout');}catch{}reset();status('יצאת מהאזור האישי');};$('refresh').onclick=load;
if(token)load();
})();
