(()=>{'use strict';
// Seller portal v2 (04.10.2026): own business only. Documents from the business
// card appear automatically; extra files are uploaded by BSD.
// 05.10.2026: "קונים מתעניינים" table — buyers matched to the owner's own business
// (display name, agreement badge, stage, materials, owner-visible notes only).
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>v?new Date(v).toLocaleDateString('he-IL',{timeZone:'Asia/Jerusalem'}):'';
let activePage='home',activityStamp=Date.now(),lastInteraction=Date.now(),activityQueue=Promise.resolve();
let token=sessionStorage.getItem('bsd-seller-token')||'',data=null,blobUrl=null,idleTimer;
const status=message=>{$('status').textContent=message;};
const errors={invalid_credentials:'שם המשתמש או הסיסמה אינם תקינים',try_later:'בוצעו ניסיונות רבים. אפשר לנסות שוב בעוד 15 דקות',unauthorized:'הכניסה פגה. יש להתחבר מחדש',strong_password_required:'יש לבחור סיסמה עם לפחות 10 תווים, אותיות ומספרים',wrong_current_password:'הסיסמה הנוכחית אינה נכונה',invalid_or_expired_link:'קישור ההפעלה אינו תקף, כבר נוצל או שפג תוקפו. אפשר לפנות לצוות BSD',not_found:'הקובץ אינו זמין כרגע',temporarily_unavailable:'השירות אינו זמין כרגע. אפשר לנסות שוב בהמשך',preview_read_only:'במצב צפייה כבעל העסק לא ניתן לשנות סיסמה או לשלוח הודעה'};
const VIEW_IMAGE=/^image\/(jpeg|png|webp|gif)$/;
const viewable=f=>f.mime==='application/pdf'||VIEW_IMAGE.test(f.mime||'');
async function api(action,payload={},file=false){
 const url=window.SELLER_PORTAL_CONFIG?.apiUrl;
 if(!url)throw Error('סביבת הבדיקה טרם חוברה לשירות המאובטח');
 const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json',...(token?{'x-seller-token':token}:{})},body:JSON.stringify({action,...payload})});
 if(file&&r.ok)return r.blob();
 const d=await r.json().catch(()=>({}));if(!r.ok){if(d.error==='password_change_required'){changePassword(true);throw Error('יש לבחור סיסמה אישית לפני צפייה במידע');}if(r.status===401&&!['login','change_password'].includes(action))reset();throw Error(errors[d.error]||'לא ניתן להשלים את הפעולה כרגע');}return d;
}
function reset(){document.body.classList.add('is-login');token='';data=null;clearTimeout(idleTimer);sessionStorage.removeItem('bsd-seller-token');$('loginPage').hidden=false;$('dashboard').hidden=true;$('logout').hidden=true;$('dialog').close();closeBlob();}
function armIdle(){if(token){clearTimeout(idleTimer);idleTimer=setTimeout(()=>{api('logout').catch(()=>{});reset();status('הכניסה הסתיימה לאחר 30 דקות ללא פעילות');},30*60000);}}
['pointerdown','keydown','scroll'].forEach(event=>document.addEventListener(event,()=>{lastInteraction=Date.now();armIdle();},{passive:true}));
function activity(kind='heartbeat'){if(data?.preview)return;const now=Date.now(),seconds=Math.min(90,Math.floor((now-activityStamp)/1000));if(kind==='heartbeat')activityStamp=now;if(!token||!data||document.hidden||now-lastInteraction>90000)return;const measuredToken=token,payload={kind,page:activePage,seconds:kind==='page_view'?0:seconds};activityQueue=activityQueue.then(async()=>{if(token===measuredToken)try{await api('activity',payload);}catch{}});}
setInterval(()=>activity(),30000);document.addEventListener('visibilitychange',()=>{activityStamp=Date.now();});
function closeBlob(){if(blobUrl){URL.revokeObjectURL(blobUrl);blobUrl=null;}}
function modal(html,wide=false){closeBlob();$('dialog').classList.toggle('pdf-dialog',wide);$('dialogBody').innerHTML=html;if(!$('dialog').open)$('dialog').showModal();}
$('closeDialog').onclick=()=>$('dialog').close();$('dialog').addEventListener('close',()=>{closeBlob();$('dialogBody').innerHTML='';});
$('showPassword').onclick=()=>{const input=$('loginForm').elements.password;const show=input.type==='password';input.type=show?'text':'password';$('showPassword').textContent=show?'🙈':'👁';$('showPassword').setAttribute('aria-pressed',String(show));$('showPassword').setAttribute('aria-label',show?'הסתרת סיסמה':'הצגת סיסמה');$('showPassword').title=show?'הסתרת סיסמה':'הצגת סיסמה';};
// forced=true: temporary password from the legacy flow (no current password needed).
function changePassword(forced=false){
 modal(`<h2>${forced?'בחירת סיסמה אישית':'החלפת סיסמה'}</h2><p>${forced?'לשמירה על המידע העסקי שלך, יש לבחור סיסמה אישית.':'אפשר להחליף את הסיסמה שקיבלת מ-BSD בסיסמה אישית שרק את/ה מכיר/ה.'}</p><form id="passwordForm">${forced?'':'<label>הסיסמה הנוכחית<input name="current" type="password" maxlength="128" autocomplete="current-password" required></label>'}<label>סיסמה חדשה<input name="password" type="password" minlength="10" maxlength="128" autocomplete="new-password" required></label><label>אימות הסיסמה החדשה<input name="confirm" type="password" minlength="10" maxlength="128" autocomplete="new-password" required></label><p class="muted">לפחות 10 תווים הכוללים אותיות ומספרים</p><p class="form-error" id="passwordError" role="alert"></p><button class="primary wide">שמירת הסיסמה</button></form>`);
 $('passwordForm').onsubmit=async e=>{e.preventDefault();const f=e.target.elements,button=e.target.querySelector('button');$('passwordError').textContent='';
  if(f.password.value!==f.confirm.value){$('passwordError').textContent='הסיסמאות החדשות אינן זהות';return;}
  button.disabled=true;try{await api('change_password',{password:f.password.value,...(forced?{}:{current_password:f.current.value})});$('dialog').close();if(forced||!data)await load();status('הסיסמה עודכנה. מהכניסה הבאה יש להשתמש בסיסמה החדשה.');}catch(err){if($('passwordError'))$('passwordError').textContent=err.message;else status(err.message);}finally{button.disabled=false;}};
}
$('loginForm').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button[type=submit]');button.disabled=true;status('');try{const d=await api('login',{username:e.target.elements.username.value.trim(),password:e.target.elements.password.value});token=d.token;sessionStorage.setItem('bsd-seller-token',token);e.target.elements.password.value='';armIdle();if(d.must_change_password)changePassword(true);else await load();}catch(err){status(err.message);}finally{button.disabled=false;}};
function selectTab(tab){if(activePage!==tab)activity();activePage=tab;activity('page_view');document.querySelectorAll('.tab').forEach(x=>x.hidden=x.id!==tab);document.querySelectorAll('.sidebar [data-tab]').forEach(x=>x.classList.toggle('selected',x.dataset.tab===tab));window.scrollTo({top:0,behavior:'smooth'});}
const EMPTY={document:'המסמכים שצוות BSD מכין עבור העסק (תקציר, הערכת שווי, חקר שוק) יופיעו כאן אוטומטית.',advertising:'דוחות פעילות שיעודכנו על ידי צוות BSD יופיעו כאן. למידע על פעילות השיווק, ניתן לפנות אלינו.',extra:'קבצים נוספים שצוות BSD ישתף איתך יופיעו כאן.'};
function filesHtml(files,kind){return files.length?files.map(f=>`<div class="file-row"><div><strong>${esc(kind==='document'?f.type:f.name)}</strong><small>${kind==='document'?esc(f.name)+' · ':''}${date(f.date)}</small>${f.period_from?`<small>תקופה: ${date(f.period_from)} עד ${date(f.period_to)}</small>`:''}</div><div class="actions">${viewable(f)?`<button data-file="${esc(f.id)}" data-mode="view">צפייה</button>`:''}<button data-file="${esc(f.id)}" data-mode="download">${f.mime==='application/pdf'?'הורדת PDF':'הורדה'}</button></div></div>`).join(''):`<p class="empty">${EMPTY[kind]}</p>`;}
const STEPS=['נמצאה התאמה','מידע ראשוני','הסכם חתום','חומרים מלאים','משא ומתן'];
function progressHtml(st){if(st.closed)return '<span class="stage-closed">התהליך הסתיים</span>';return `<span class="steps" role="img" aria-label="שלב ${st.step} מתוך 5">${STEPS.map((x,i)=>`<i class="${i<st.step?'on':''}" title="${esc(x)}"></i>`).join('')}</span>`;}
function agreementHtml(a){return `<span class="agr agr-${esc(a.key)}">${a.key==='signed'?'✓ ':''}${esc(a.label)}</span>${a.date?`<small>${date(a.date)}</small>`:''}`;}
function materialsHtml(m){return `<span class="mat mat-${esc(m.level)}">${esc(m.label)}</span>${m.items.length?`<ul class="mat-items">${m.items.map(x=>`<li>${esc(x.label)}${x.date?` <small>${date(x.date)}</small>`:''}</li>`).join('')}</ul>`:''}`;}
function notesHtml(n){return n.length?n.map(x=>`<p class="m-note">${esc(x.text)}${x.date?` <small>${date(x.date)}</small>`:''}</p>`).join(''):'<span class="muted">—</span>';}
function matchesHtml(rows){if(!rows.length)return '<p class="empty">כשצוות BSD יציג את העסק לקונים מתאימים, הם יופיעו כאן עם השלב שבו כל אחד נמצא.</p>';
 return `<div class="match-table" role="table" aria-label="קונים מתעניינים"><div class="mt-head" role="row"><span role="columnheader">#</span><span role="columnheader">קונה</span><span role="columnheader">הסכם</span><span role="columnheader">שלב בתהליך</span><span role="columnheader">חומרים שנמסרו</span><span role="columnheader">עודכן</span><span role="columnheader">הערות</span></div>${rows.map(r=>`<div class="mt-row${r.stage.closed?' closed':''}" role="row"><span class="mt-ref" role="cell">${esc(r.ref)}</span><span class="mt-buyer" role="cell" data-label="קונה"><strong>${esc(r.buyer)}</strong></span><span role="cell" data-label="הסכם">${agreementHtml(r.agreement)}</span><span role="cell" data-label="שלב בתהליך"><strong class="stage-label">${esc(r.stage.label)}</strong>${progressHtml(r.stage)}</span><span role="cell" data-label="חומרים שנמסרו">${materialsHtml(r.materials)}</span><span role="cell" data-label="עודכן">${date(r.updated_at)}</span><span role="cell" data-label="הערות">${notesHtml(r.notes)}</span></div>`).join('')}</div>`;}
function summaryHtml(s){return [['קונים שקיבלו את העסק לבדיקה',s.total],['בתהליך פעיל',s.active],['חתמו על הסכם',s.signed],['קיבלו חומרים מלאים',s.full]].map(([k,v])=>`<div><b>${esc(v)}</b><span>${esc(k)}</span></div>`).join('');}
// «איפה העסק מופץ» (08.10.2026): three channels ticked per deal by BSD staff in the CRM.
// The API sends booleans only. The two texts below are Baruch's exact wording.
const DIST_CHANNELS=[['vip','הופץ ללקוחות VIP'],['agents','הופץ לכל סוכני BSD'],['media','הופץ במערכות המדיה של BSD']];
const DIST_FIRST='החשיפה הראשונה מתבצעת מול קונים פוטנציאליים הרשומים במאגר הקונים של החברה.';
const DIST_PRIVACY='בכל ערוצי הפרסום החומרים מוצגים תמיד באופן אנונימי. המידע המלא והאמיתי על העסק נמסר אך ורק למי שחתם על הסכם שמירת סודיות מול החברה, ורק לאחר בחינה מעמיקה של יכולותיו ושל רצונו האמיתי לרכוש את העסק.';
const DIST_NOT_STARTED='ההפצה עדיין לא התחילה. ברגע שתתחיל, הערוצים יסומנו כאן.';
// Same section on every portal: always 3 channels, then ONE line, then the privacy paragraph.
// ✓ only for a strict true from the API; anything else (missing, null, error) is «טרם בוצע».
// The single line: first-exposure text if any channel is ✓, otherwise the not-started text.
function distributionHtml(d){const ch=(d&&typeof d==='object'&&d.channels&&typeof d.channels==='object')?d.channels:{};
 const on=k=>ch[k]===true,started=DIST_CHANNELS.some(([k])=>on(k));
 return `<ul class="dist-channels">${DIST_CHANNELS.map(([k,label])=>`<li class="dist-channel ${on(k)?'on':'off'}"><span class="dist-mark" aria-hidden="true">${on(k)?'✓':''}</span><span class="dist-label">${esc(label)}</span><span class="dist-state">${on(k)?'בוצע':'טרם בוצע'}</span></li>`).join('')}</ul>`
  +(started?`<p class="dist-first">${esc(DIST_FIRST)}</p>`:`<p class="muted dist-note">${esc(DIST_NOT_STARTED)}</p>`)
  +`<p class="dist-privacy">${esc(DIST_PRIVACY)}</p>`;}
async function load(){try{data=await api('dashboard');const b=data.business,by=k=>data.files.filter(f=>f.kind===k),docs=by('document'),reports=by('advertising'),extras=by('extra');
 const banner=$('previewBanner');if(banner)banner.hidden=!data.preview;document.querySelectorAll('[data-change-password],[data-message]').forEach(el=>{el.hidden=!!data.preview;});
 document.body.classList.remove('is-login');$('loginPage').hidden=true;$('dashboard').hidden=false;$('logout').hidden=false;$('businessName').textContent=b.internal_name;$('hello').textContent=b.owner_name?`שלום, ${b.owner_name}`:'ברוכים הבאים';$('businessMeta').textContent=[b.owner_name,b.owner_phone,b.city].filter(Boolean).join(' · ');
 $('docCount').textContent=docs.length||'טרם עודכנו';$('extraCount').textContent=extras.length||'אין עדיין';$('reportCount').textContent=reports.length||'טרם עודכנו';
 const matches=data.matches||[],ms=data.match_summary||{total:matches.length,active:0,signed:0,full:0};$('matchCount').textContent=ms.total||'אין עדיין';$('matchSummary').innerHTML=matches.length?summaryHtml(ms):'';$('matchList').innerHTML=data.matches_unavailable?'<p class="empty">טבלת הקונים אינה זמינה כרגע. אפשר לרענן בעוד כמה דקות או לפנות לצוות BSD.</p>':matchesHtml(matches);
 const dist=distributionHtml(data.distribution);$('homeDistribution').innerHTML=dist;$('reportsDistribution').innerHTML=dist;
 $('documentList').innerHTML=filesHtml(docs,'document');$('extraList').innerHTML=filesHtml(extras,'extra');$('reportList').innerHTML=filesHtml(reports,'advertising');$('homeFiles').innerHTML=filesHtml(docs.slice(0,4),'document');$('homeExtras').innerHTML=filesHtml(extras.slice(0,3),'extra');
 $('businessDetails').innerHTML=[['שם העסק',b.internal_name],['איש קשר',b.owner_name],['טלפון',b.owner_phone],['מיקום',b.city]].filter(x=>x[1]).map(([k,v])=>`<dt>${esc(k)}</dt><dd>${esc(v)}</dd>`).join('');
 $('updateMessage').textContent=data.update?.message||'ניתן לפנות לצוות BSD לקבלת מידע על תהליך מכירת העסק.';$('updateTitle').textContent=data.update?'עדכון מצוות BSD':'עדכונים אישיים יופיעו כאן';$('updateDate').textContent=date(data.update?.date);
 const phone=String(data.contact.phone||'').replace(/[^+0-9]/g,'');if(phone){$('phone').href='tel:'+phone;$('phone').textContent=data.contact.phone;$('phone').hidden=false;const wa=phone.startsWith('0')?'972'+phone.slice(1):phone.replace('+','');$('whatsapp').href=`https://wa.me/${wa}?text=${encodeURIComponent('שלום BSD, אני פונה מהאזור האישי של '+b.internal_name)}`;$('whatsapp').hidden=false;}
 selectTab(activePage);armIdle();status('');}catch(err){status(err.message);}}
async function openFile(id,mode){const f=data?.files.find(x=>x.id===id);if(!f)return;status('טוען את הקובץ...');try{const blob=await api('file',{file_id:id,mode,file_source:f.file_source},true);const url=URL.createObjectURL(blob);
 if(mode==='download'||!viewable(f)){const a=document.createElement('a');a.href=url;a.download=f.name||'file';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);}
 else if(f.mime==='application/pdf'){modal(`<h2>${esc(f.name)}</h2><p class="muted">אם התצוגה אינה מופיעה במכשיר שלך, ניתן לפתוח את הקובץ בחלון נפרד או להוריד אותו.</p><a id="openPdf" target="_blank" rel="noopener">פתיחה בחלון נפרד</a><button data-file="${esc(id)}" data-mode="download">הורדת PDF</button><iframe title="תצוגת מסמך PDF" id="pdfFrame"></iframe>`,true);blobUrl=url;$('pdfFrame').src=url;$('openPdf').href=url;}
 else{modal(`<h2>${esc(f.name)}</h2><button data-file="${esc(id)}" data-mode="download">הורדה</button><img id="imageView" class="image-view" alt="${esc(f.name)}">`,true);blobUrl=url;$('imageView').src=url;}
 status('');}catch(err){status(err.message);}}
document.addEventListener('click',e=>{const tab=e.target.closest('[data-tab]');if(tab)selectTab(tab.dataset.tab);const file=e.target.closest('[data-file]');if(file)openFile(file.dataset.file,file.dataset.mode);if(e.target.closest('[data-change-password]'))changePassword(false);
 const rec=e.target.closest('[data-recovery]');if(rec){const kind=rec.dataset.recovery;modal(`<h2>${kind==='username'?'שחזור שם משתמש':'איפוס סיסמה'}</h2><p>הבקשה תועבר לצוות BSD. פרטי חשבונות אינם נחשפים בטופס זה.</p><form id="recoveryForm"><label>שם המבקש<input name="name" maxlength="100" required autocomplete="name"></label><label>שם העסק<input name="business" maxlength="160" required></label><label>טלפון<input name="phone" type="tel" maxlength="25" required autocomplete="tel"></label><label>הערה אופציונלית<textarea name="message" maxlength="2000"></textarea></label><button class="primary wide">שליחת בקשה</button></form>`);$('recoveryForm').onsubmit=async ev=>{ev.preventDefault();try{await api('recovery',{kind,...Object.fromEntries(new FormData(ev.target))});$('dialog').close();status('הבקשה התקבלה ותועבר לצוות BSD');}catch(err){status(err.message);}};}
 if(e.target.closest('[data-message]')){modal('<h2>שליחת הודעה לצוות BSD</h2><p>הפנייה תישלח עם שם העסק ופרטי החשבון שלך.</p><form id="messageForm"><label>ההודעה שלך<textarea name="message" maxlength="2000" required rows="5"></textarea></label><button class="primary wide">שליחת הודעה</button></form>');$('messageForm').onsubmit=async ev=>{ev.preventDefault();try{await api('message',{message:ev.target.elements.message.value});$('dialog').close();status('ההודעה התקבלה במערכת BSD');}catch(err){status(err.message);}};}});
// Legacy one-time activation link (#activate=<secret>) for accounts opened before
// 04.10.2026. The fragment is never sent to the web server and is removed at once.
function activation(){const m=/^#activate=([A-Za-z0-9]{43})$/.exec(location.hash);if(!m)return false;const secret=m[1];history.replaceState(null,'',location.pathname+location.search);
 modal('<h2>הפעלת האזור האישי</h2><p>ברוכים הבאים לאזור האישי של BSD. כדי להפעיל את החשבון, יש לבחור סיסמה אישית.</p><form id="activateForm"><label>סיסמה חדשה<input name="password" type="password" minlength="10" maxlength="128" autocomplete="new-password" required></label><label>אימות הסיסמה<input name="confirm" type="password" minlength="10" maxlength="128" autocomplete="new-password" required></label><p class="muted">לפחות 10 תווים הכוללים אותיות ומספרים. הקישור פועל פעם אחת בלבד.</p><button class="primary wide">הפעלת החשבון</button></form>');
 $('activateForm').onsubmit=async e=>{e.preventDefault();const f=e.target.elements;if(f.password.value!==f.confirm.value){status('הסיסמאות אינן זהות');return;}const button=e.target.querySelector('button');button.disabled=true;try{const d=await api('activate',{token:secret,password:f.password.value});token=d.token;sessionStorage.setItem('bsd-seller-token',token);$('dialog').close();armIdle();await load();status('החשבון הופעל. שם המשתמש שלך לכניסות הבאות: '+d.username);}catch(err){status(err.message);}finally{button.disabled=false;}};
 return true;}
$('logout').onclick=async()=>{try{await api('logout');}catch{}reset();status('יצאת מהאזור האישי');};$('refresh').onclick=load;
// Admin QA entry (#preview=<token>). The fragment is removed at once and is not a login.
function takePreview(){const m=/^#preview=([A-HJ-NP-Za-km-np-z2-9]{48})$/.exec(location.hash);if(!m)return false;token=m[1];sessionStorage.setItem('bsd-seller-token',token);history.replaceState(null,'',location.pathname+location.search);return true;}
if(takePreview())load();
else if(!activation()&&token)load();
})();
